- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_intensity_max
    - temperature
    - apparent_temperature 
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - sunrise_time
    - sunset_time
    - nearest_storm_distance
    - nearest_storm_bearing
    - alerts 

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'     

- platform: mqtt
  name: "Node RED"
  state_topic: "checkIn/nodeRED"
  expire_after: 300

- platform: here_travel_time
  name: Justin to Justin's Work
  route_mode: fastest
  app_id: "J28BOeSwTNtkPs7Ahx6G"
  app_code: "9Mn4WptP7fCURQEIKNSG9g"
  origin_entity_id: device_tracker.life360_justin
  destination_entity_id: zone.watson_clinic_wcpc

- platform: here_travel_time
  name: Justin to Home
  route_mode: fastest
  app_id: "J28BOeSwTNtkPs7Ahx6G"
  app_code: "9Mn4WptP7fCURQEIKNSG9g"
  origin_entity_id: device_tracker.life360_justin
  destination_entity_id: zone.home  
